// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7fjM3ZlGeSdghCqdf-cxTZbVWAVTcuLY',
    appId: '1:495985397843:web:dfcf08ac2d0bf6f984b6a6',
    messagingSenderId: '495985397843',
    projectId: 'pharmafinderapp-15977',
    authDomain: 'pharmafinderapp-15977.firebaseapp.com',
    storageBucket: 'pharmafinderapp-15977.firebasestorage.app',
    measurementId: 'G-2ES426KK9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx98Sppzous_oOciVWio7It_KUc6Y-4h4',
    appId: '1:495985397843:android:1cea9cf9c99f999e84b6a6',
    messagingSenderId: '495985397843',
    projectId: 'pharmafinderapp-15977',
    storageBucket: 'pharmafinderapp-15977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh-fTu0ZHHYaQTOhPqAI9g9pUyW_5Vi-E',
    appId: '1:495985397843:ios:bf8ee483cbe7be6184b6a6',
    messagingSenderId: '495985397843',
    projectId: 'pharmafinderapp-15977',
    storageBucket: 'pharmafinderapp-15977.firebasestorage.app',
    iosBundleId: 'com.example.pharmaFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh-fTu0ZHHYaQTOhPqAI9g9pUyW_5Vi-E',
    appId: '1:495985397843:ios:bf8ee483cbe7be6184b6a6',
    messagingSenderId: '495985397843',
    projectId: 'pharmafinderapp-15977',
    storageBucket: 'pharmafinderapp-15977.firebasestorage.app',
    iosBundleId: 'com.example.pharmaFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7fjM3ZlGeSdghCqdf-cxTZbVWAVTcuLY',
    appId: '1:495985397843:web:915dd219d87a8ac084b6a6',
    messagingSenderId: '495985397843',
    projectId: 'pharmafinderapp-15977',
    authDomain: 'pharmafinderapp-15977.firebaseapp.com',
    storageBucket: 'pharmafinderapp-15977.firebasestorage.app',
    measurementId: 'G-PWJM84RLED',
  );
}
